package stni.atlassian.remote.jira;
public interface JiraService{
  String getBaseUrl();
  void addActorsToProjectRole(java.lang.String[] string1,com.atlassian.jira.rpc.soap.beans.RemoteProjectRole remoteProjectRole2,com.atlassian.jira.rpc.soap.beans.RemoteProject remoteProject3,java.lang.String string4);
  boolean addAttachmentsToIssue(java.lang.String string1,java.lang.String[] string2,byte[][] byte3);
  boolean addBase64EncodedAttachmentsToIssue(java.lang.String string1,java.lang.String[] string2,java.lang.String[] string3);
  void addComment(java.lang.String string1,com.atlassian.jira.rpc.soap.beans.RemoteComment remoteComment2);
  void addDefaultActorsToProjectRole(java.lang.String[] string1,com.atlassian.jira.rpc.soap.beans.RemoteProjectRole remoteProjectRole2,java.lang.String string3);
  com.atlassian.jira.rpc.soap.beans.RemotePermissionScheme addPermissionTo(com.atlassian.jira.rpc.soap.beans.RemotePermissionScheme remotePermissionScheme1,com.atlassian.jira.rpc.soap.beans.RemotePermission remotePermission2,com.atlassian.jira.rpc.soap.beans.RemoteEntity remoteEntity3);
  void addUserToGroup(com.atlassian.jira.rpc.soap.beans.RemoteGroup remoteGroup1,com.atlassian.jira.rpc.soap.beans.RemoteUser remoteUser2);
  com.atlassian.jira.rpc.soap.beans.RemoteVersion addVersion(java.lang.String string1,com.atlassian.jira.rpc.soap.beans.RemoteVersion remoteVersion2);
  com.atlassian.jira.rpc.soap.beans.RemoteWorklog addWorklogAndAutoAdjustRemainingEstimate(java.lang.String string1,com.atlassian.jira.rpc.soap.beans.RemoteWorklog remoteWorklog2);
  com.atlassian.jira.rpc.soap.beans.RemoteWorklog addWorklogAndRetainRemainingEstimate(java.lang.String string1,com.atlassian.jira.rpc.soap.beans.RemoteWorklog remoteWorklog2);
  com.atlassian.jira.rpc.soap.beans.RemoteWorklog addWorklogWithNewRemainingEstimate(java.lang.String string1,com.atlassian.jira.rpc.soap.beans.RemoteWorklog remoteWorklog2,java.lang.String string3);
  void archiveVersion(java.lang.String string1,java.lang.String string2,boolean boolean3);
  com.atlassian.jira.rpc.soap.beans.RemoteGroup createGroup(java.lang.String string1,com.atlassian.jira.rpc.soap.beans.RemoteUser remoteUser2);
  com.atlassian.jira.rpc.soap.beans.RemoteIssue createIssue(com.atlassian.jira.rpc.soap.beans.RemoteIssue remoteIssue1);
  com.atlassian.jira.rpc.soap.beans.RemoteIssue createIssueWithParent(com.atlassian.jira.rpc.soap.beans.RemoteIssue remoteIssue1,java.lang.String string2);
  com.atlassian.jira.rpc.soap.beans.RemoteIssue createIssueWithParentWithSecurityLevel(com.atlassian.jira.rpc.soap.beans.RemoteIssue remoteIssue1,java.lang.String string2,long long3);
  com.atlassian.jira.rpc.soap.beans.RemoteIssue createIssueWithSecurityLevel(com.atlassian.jira.rpc.soap.beans.RemoteIssue remoteIssue1,long long2);
  com.atlassian.jira.rpc.soap.beans.RemotePermissionScheme createPermissionScheme(java.lang.String string1,java.lang.String string2);
  com.atlassian.jira.rpc.soap.beans.RemoteProject createProject(java.lang.String string1,java.lang.String string2,java.lang.String string3,java.lang.String string4,java.lang.String string5,com.atlassian.jira.rpc.soap.beans.RemotePermissionScheme remotePermissionScheme6,com.atlassian.jira.rpc.soap.beans.RemoteScheme remoteScheme7,com.atlassian.jira.rpc.soap.beans.RemoteScheme remoteScheme8);
  com.atlassian.jira.rpc.soap.beans.RemoteProject createProjectFromObject(com.atlassian.jira.rpc.soap.beans.RemoteProject remoteProject1);
  com.atlassian.jira.rpc.soap.beans.RemoteProjectRole createProjectRole(com.atlassian.jira.rpc.soap.beans.RemoteProjectRole remoteProjectRole1);
  com.atlassian.jira.rpc.soap.beans.RemoteUser createUser(java.lang.String string1,java.lang.String string2,java.lang.String string3,java.lang.String string4);
  void deleteGroup(java.lang.String string1,java.lang.String string2);
  void deleteIssue(java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemotePermissionScheme deletePermissionFrom(com.atlassian.jira.rpc.soap.beans.RemotePermissionScheme remotePermissionScheme1,com.atlassian.jira.rpc.soap.beans.RemotePermission remotePermission2,com.atlassian.jira.rpc.soap.beans.RemoteEntity remoteEntity3);
  void deletePermissionScheme(java.lang.String string1);
  void deleteProject(java.lang.String string1);
  void deleteProjectAvatar(long long1);
  void deleteProjectRole(com.atlassian.jira.rpc.soap.beans.RemoteProjectRole remoteProjectRole1,boolean boolean2);
  void deleteUser(java.lang.String string1);
  void deleteWorklogAndAutoAdjustRemainingEstimate(java.lang.String string1);
  void deleteWorklogAndRetainRemainingEstimate(java.lang.String string1);
  void deleteWorklogWithNewRemainingEstimate(java.lang.String string1,java.lang.String string2);
  com.atlassian.jira.rpc.soap.beans.RemoteComment editComment(com.atlassian.jira.rpc.soap.beans.RemoteComment remoteComment1);
  com.atlassian.jira.rpc.soap.beans.RemotePermission[] getAllPermissions();
  com.atlassian.jira.rpc.soap.beans.RemoteScheme[] getAssociatedNotificationSchemes(com.atlassian.jira.rpc.soap.beans.RemoteProjectRole remoteProjectRole1);
  com.atlassian.jira.rpc.soap.beans.RemoteScheme[] getAssociatedPermissionSchemes(com.atlassian.jira.rpc.soap.beans.RemoteProjectRole remoteProjectRole1);
  com.atlassian.jira.rpc.soap.beans.RemoteAttachment[] getAttachmentsFromIssue(java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemoteNamedObject[] getAvailableActions(java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemoteComment getComment(long long1);
  com.atlassian.jira.rpc.soap.beans.RemoteComment[] getComments(java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemoteComponent[] getComponents(java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemoteConfiguration getConfiguration();
  com.atlassian.jira.rpc.soap.beans.RemoteField[] getCustomFields();
  com.atlassian.jira.rpc.soap.beans.RemoteRoleActors getDefaultRoleActors(com.atlassian.jira.rpc.soap.beans.RemoteProjectRole remoteProjectRole1);
  com.atlassian.jira.rpc.soap.beans.RemoteFilter[] getFavouriteFilters();
  com.atlassian.jira.rpc.soap.beans.RemoteField[] getFieldsForAction(java.lang.String string1,java.lang.String string2);
  com.atlassian.jira.rpc.soap.beans.RemoteField[] getFieldsForCreate(java.lang.String string1,long long2);
  com.atlassian.jira.rpc.soap.beans.RemoteField[] getFieldsForEdit(java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemoteGroup getGroup(java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemoteIssue getIssue(java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemoteIssue getIssueById(java.lang.String string1);
  long getIssueCountForFilter(java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemoteIssueType[] getIssueTypes();
  com.atlassian.jira.rpc.soap.beans.RemoteIssueType[] getIssueTypesForProject(java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemoteIssue[] getIssuesFromFilter(java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemoteIssue[] getIssuesFromFilterWithLimit(java.lang.String string1,int int2,int int3);
  com.atlassian.jira.rpc.soap.beans.RemoteIssue[] getIssuesFromJqlSearch(java.lang.String string1,int int2);
  com.atlassian.jira.rpc.soap.beans.RemoteIssue[] getIssuesFromTextSearch(java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemoteIssue[] getIssuesFromTextSearchWithLimit(java.lang.String string1,int int2,int int3);
  com.atlassian.jira.rpc.soap.beans.RemoteIssue[] getIssuesFromTextSearchWithProject(java.lang.String[] string1,java.lang.String string2,int int3);
  com.atlassian.jira.rpc.soap.beans.RemoteScheme[] getNotificationSchemes();
  com.atlassian.jira.rpc.soap.beans.RemotePermissionScheme[] getPermissionSchemes();
  com.atlassian.jira.rpc.soap.beans.RemotePriority[] getPriorities();
  com.atlassian.jira.rpc.soap.beans.RemoteAvatar getProjectAvatar(java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemoteAvatar[] getProjectAvatars(java.lang.String string1,boolean boolean2);
  com.atlassian.jira.rpc.soap.beans.RemoteProject getProjectById(long long1);
  com.atlassian.jira.rpc.soap.beans.RemoteProject getProjectByKey(java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemoteProjectRole getProjectRole(long long1);
  com.atlassian.jira.rpc.soap.beans.RemoteProjectRoleActors getProjectRoleActors(com.atlassian.jira.rpc.soap.beans.RemoteProjectRole remoteProjectRole1,com.atlassian.jira.rpc.soap.beans.RemoteProject remoteProject2);
  com.atlassian.jira.rpc.soap.beans.RemoteProjectRole[] getProjectRoles();
  com.atlassian.jira.rpc.soap.beans.RemoteProject getProjectWithSchemesById(long long1);
  com.atlassian.jira.rpc.soap.beans.RemoteProject[] getProjectsNoSchemes();
  java.util.Calendar getResolutionDateById(long long1);
  java.util.Calendar getResolutionDateByKey(java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemoteResolution[] getResolutions();
  com.atlassian.jira.rpc.soap.beans.RemoteFilter[] getSavedFilters();
  com.atlassian.jira.rpc.soap.beans.RemoteSecurityLevel getSecurityLevel(java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemoteSecurityLevel[] getSecurityLevels(java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemoteScheme[] getSecuritySchemes();
  com.atlassian.jira.rpc.soap.beans.RemoteServerInfo getServerInfo();
  com.atlassian.jira.rpc.soap.beans.RemoteStatus[] getStatuses();
  com.atlassian.jira.rpc.soap.beans.RemoteIssueType[] getSubTaskIssueTypes();
  com.atlassian.jira.rpc.soap.beans.RemoteIssueType[] getSubTaskIssueTypesForProject(java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemoteUser getUser(java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemoteVersion[] getVersions(java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemoteWorklog[] getWorklogs(java.lang.String string1);
  boolean hasPermissionToCreateWorklog(java.lang.String string1);
  boolean hasPermissionToDeleteWorklog(java.lang.String string1);
  boolean hasPermissionToEditComment(com.atlassian.jira.rpc.soap.beans.RemoteComment remoteComment1);
  boolean hasPermissionToUpdateWorklog(java.lang.String string1);
  boolean isProjectRoleNameUnique(java.lang.String string1);
  java.lang.String login(java.lang.String string1);
  boolean logout();
  com.atlassian.jira.rpc.soap.beans.RemoteIssue progressWorkflowAction(java.lang.String string1,java.lang.String string2,com.atlassian.jira.rpc.soap.beans.RemoteFieldValue[] remoteFieldValue3);
  void refreshCustomFields();
  void releaseVersion(java.lang.String string1,com.atlassian.jira.rpc.soap.beans.RemoteVersion remoteVersion2);
  void removeActorsFromProjectRole(java.lang.String[] string1,com.atlassian.jira.rpc.soap.beans.RemoteProjectRole remoteProjectRole2,com.atlassian.jira.rpc.soap.beans.RemoteProject remoteProject3,java.lang.String string4);
  void removeAllRoleActorsByNameAndType(java.lang.String string1,java.lang.String string2);
  void removeAllRoleActorsByProject(com.atlassian.jira.rpc.soap.beans.RemoteProject remoteProject1);
  void removeDefaultActorsFromProjectRole(java.lang.String[] string1,com.atlassian.jira.rpc.soap.beans.RemoteProjectRole remoteProjectRole2,java.lang.String string3);
  void removeUserFromGroup(com.atlassian.jira.rpc.soap.beans.RemoteGroup remoteGroup1,com.atlassian.jira.rpc.soap.beans.RemoteUser remoteUser2);
  void setNewProjectAvatar(java.lang.String string1,java.lang.String string2,java.lang.String string3);
  void setProjectAvatar(java.lang.String string1,long long2);
  void setUserPassword(com.atlassian.jira.rpc.soap.beans.RemoteUser remoteUser1,java.lang.String string2);
  com.atlassian.jira.rpc.soap.beans.RemoteGroup updateGroup(com.atlassian.jira.rpc.soap.beans.RemoteGroup remoteGroup1);
  com.atlassian.jira.rpc.soap.beans.RemoteIssue updateIssue(java.lang.String string1,com.atlassian.jira.rpc.soap.beans.RemoteFieldValue[] remoteFieldValue2);
  com.atlassian.jira.rpc.soap.beans.RemoteProject updateProject(com.atlassian.jira.rpc.soap.beans.RemoteProject remoteProject1);
  void updateProjectRole(com.atlassian.jira.rpc.soap.beans.RemoteProjectRole remoteProjectRole1);
  com.atlassian.jira.rpc.soap.beans.RemoteUser updateUser(com.atlassian.jira.rpc.soap.beans.RemoteUser remoteUser1);
  void updateWorklogAndAutoAdjustRemainingEstimate(com.atlassian.jira.rpc.soap.beans.RemoteWorklog remoteWorklog1);
  void updateWorklogAndRetainRemainingEstimate(com.atlassian.jira.rpc.soap.beans.RemoteWorklog remoteWorklog1);
  void updateWorklogWithNewRemainingEstimate(com.atlassian.jira.rpc.soap.beans.RemoteWorklog remoteWorklog1,java.lang.String string2);
  java.lang.Object executeGet(java.lang.String string0);
  java.lang.Object executePost(java.lang.String string0,java.lang.Object object1);
  java.util.List<java.util.Map<java.lang.String, java.lang.Object>> getAllIssuesByJql(java.lang.String string0,java.lang.String string1,java.lang.String string2);
  java.util.List<com.atlassian.jira.rpc.soap.beans.RemoteProject> getAllProjects();
  java.util.List<stni.atlassian.remote.jira.rest.IssueLinkType> getIssueLinkTypes();
  java.util.List<java.util.Map<java.lang.String, java.lang.Object>> getIssuesByJql(java.lang.String string0,int int1,int int2,java.lang.String string3,java.lang.String string4);
  java.util.List<com.atlassian.jira.rpc.soap.beans.RemoteProject> getProjectsByKey(java.lang.String... string0);
  void linkIssues(stni.atlassian.remote.jira.rest.IssueLink issueLink0);
  java.io.InputStream loadAttachment(com.atlassian.jira.rpc.soap.beans.RemoteAttachment remoteAttachment0);
  com.atlassian.jira.rpc.soap.beans.RemoteNamedObject actionByName(java.lang.String string0,java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemoteIssue createRequirementAndFeature(com.atlassian.jira.rpc.soap.beans.RemoteProject remoteProject0,java.lang.String string1,java.lang.String string2);
  java.lang.String customFieldByName(com.atlassian.jira.rpc.soap.beans.RemoteIssue remoteIssue0,java.lang.String string1);
  java.lang.String fieldNameById(java.lang.String string0);
  com.atlassian.jira.rpc.soap.beans.RemoteIssue[] getIssues(com.atlassian.jira.rpc.soap.beans.RemoteProject remoteProject0,com.atlassian.jira.rpc.soap.beans.RemoteVersion remoteVersion1,boolean boolean2);
  stni.atlassian.remote.jira.JiraService getService();
  com.atlassian.jira.rpc.soap.beans.RemoteIssueType issueTypeById(java.lang.String string0);
  com.atlassian.jira.rpc.soap.beans.RemoteIssueType issueTypeByName(java.lang.String string0);
  java.lang.String makeReleaseNotes(com.atlassian.jira.rpc.soap.beans.RemoteProject remoteProject0,com.atlassian.jira.rpc.soap.beans.RemoteVersion remoteVersion1,boolean boolean2);
  com.atlassian.jira.rpc.soap.beans.RemotePriority priorityById(java.lang.String string0);
  com.atlassian.jira.rpc.soap.beans.RemoteIssue progressStatusAction(java.lang.String string0,java.lang.String string1,java.lang.String string2);
  com.atlassian.jira.rpc.soap.beans.RemoteSecurityLevel securityLevelByName(com.atlassian.jira.rpc.soap.beans.RemoteProject remoteProject0,java.lang.String string1);
  com.atlassian.jira.rpc.soap.beans.RemoteStatus statusById(java.lang.String string0);
  com.atlassian.jira.rpc.soap.beans.RemoteStatus statusByName(java.lang.String string0);
  long timeToResolve(com.atlassian.jira.rpc.soap.beans.RemoteIssue remoteIssue0);
  com.atlassian.jira.rpc.soap.beans.RemoteVersion versionByName(com.atlassian.jira.rpc.soap.beans.RemoteProject remoteProject0,java.lang.String string1);
}
